version: "3"
services:
  nginx:
    image: nginx
    depends_on:
      - apache_a
      - apache_b
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/logs:/usr/local/logs
    networks:
      - frontend
    ports:
      - 80:80

  apache_a:
    image: httpd:2.4-alpine
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
    expose:
      - 80
    volumes:
      - ./apache/config/tourradar.local.conf:/usr/local/apache2/conf.d/tourradar.local.conf:ro
      - ./apache/logs/:/usr/local/apache2/logs
      - ./php/public_html/:/var/www/html/

  apache_b:
    image: httpd:2.4-alpine
    build: './apache/'
    depends_on:
      - php
    networks:
      - frontend
    expose:
      - 80
    volumes:
      - ./apache/config/tourradar.local.conf:/usr/local/apache2/conf.d/tourradar.local.conf:ro
      - ./apache/logs/:/usr/local/apache2/logs
      - ./php/public_html/:/var/www/html/


  php:
    build: './php/'
    networks:
      - frontend
      - redis
    volumes:
      - ./php/public_html/:/var/www/html/    
      - ./php/config/session.ini:/usr/local/etc/php/conf.d/session.ini:ro

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    networks:
      - redis
    volumes:
      - ./redis/data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.6.1
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5044:5044"
      - "9600:9600"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  filebeat:
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:6.6.1
    volumes:
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./apache/logs:/var/log/apache2/
      - ./filebeat/data:/usr/share/filebeat/data/
    networks: 
      - elk
    command: filebeat -e -strict.perms=false
    restart: on-failure
    depends_on:
      - elasticsearch


  jenkins:
    image: jenkins/jenkins:lts
    build: './jenkins/'
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/jenkins.yaml
    ports:
      - '8080:8080'
    networks: 
      - elk
    volumes:
      - ./jenkins/config/jobs:/jobs/
      - ./jenkins/config/jenkins.yaml:/var/jenkins_home/jenkins.yaml:ro

networks:
  frontend:
  redis:
  elk:
